QT += core widgets uitools printsupport opengl openglwidgets network testlib
TEMPLATE = app
CONFIG += testcase console c++11
DEFINES += LABANALYSER_PLUGIN_LEASE_TESTING
TARGET = PluginLoaderContractTests
REPOSITORY_ROOT = $$clean_path($$PWD/../../..)
INCLUDEPATH += $$REPOSITORY_ROOT $$REPOSITORY_ROOT/src $$REPOSITORY_ROOT/src/DropWidgets $$REPOSITORY_ROOT/src
SOURCES += PluginLoaderContractTests.cpp DataManagementSetClassTestSeam.cpp $$REPOSITORY_ROOT/src/LoadSave/loadplugin.cpp $$REPOSITORY_ROOT/src/LoadSave/PluginLeasePool.cpp $$REPOSITORY_ROOT/src/DataManagement/ContainerStore.cpp $$REPOSITORY_ROOT/src/DataManagement/DataRegistry.cpp $$REPOSITORY_ROOT/src/DataManagement/DeviceRegistry.cpp $$REPOSITORY_ROOT/src/DataManagement/WidgetBindingRegistry.cpp $$REPOSITORY_ROOT/src/DataManagement/MessageDispatchPolicy.cpp $$REPOSITORY_ROOT/src/DataManagement/DataManagementClass.cpp $$REPOSITORY_ROOT/src/DataManagement/DataMessengerClass.cpp $$REPOSITORY_ROOT/src/plugins/InterfaceDataType.cpp
HEADERS += $$REPOSITORY_ROOT/src/LoadSave/loadplugin.h $$REPOSITORY_ROOT/src/LoadSave/PluginLeasePool.h $$REPOSITORY_ROOT/src/DataManagement/ContainerStore.h $$REPOSITORY_ROOT/src/DataManagement/DataRegistry.h $$REPOSITORY_ROOT/src/DataManagement/DeviceRegistry.h $$REPOSITORY_ROOT/src/DataManagement/WidgetBindingRegistry.h $$REPOSITORY_ROOT/src/DataManagement/MessageDispatchPolicy.h $$REPOSITORY_ROOT/src/DataManagement/DataManagementClass.h $$REPOSITORY_ROOT/src/DataManagement/DataManagementSetClass.h $$REPOSITORY_ROOT/src/DataManagement/DataMessengerClass.h $$REPOSITORY_ROOT/src/DataManagement/mapper.h $$REPOSITORY_ROOT/src/plugins/platforminterface.h $$REPOSITORY_ROOT/src/plugins/InterfaceDataType.h
